In [2]:
import torch

x = torch.randn(3, requires_grad= True)
print(x)

tensor([ 1.7553, -0.7191,  1.6576], requires_grad=True)


In [3]:
y = x+2
print(y)

tensor([3.7553, 1.2809, 3.6576], grad_fn=<AddBackward0>)


In [5]:
z = y*y*2
z = z.mean()
print(z)

tensor(19.4143, grad_fn=<MeanBackward0>)


In [6]:
z.backward() #dz/dx
print(x.grad)

tensor([5.0071, 1.7079, 4.8768])


In [7]:
#Autograd function applying three methods
#that how can we prevent the tracking the gradient
# 1. x.requires_grad(False)
# 2. x.detach()
# 3. with torch.no_grad()


In [8]:
#x.requires_grad(Flase) it means it will modify the variable inplace
#x.requires_grad_(False)
#print(x)

tensor([ 1.7553, -0.7191,  1.6576])


In [9]:
#x.detach()
#y = x.detach()
#print(y)

tensor([ 1.7553, -0.7191,  1.6576])


In [11]:
#with torch.no_grad()
#with torch.no_grad():
y = y+2
print(y)

tensor([5.7553, 3.2809, 5.6576])


In [17]:
#Must Know during training Model
weights = torch.ones(4, requires_grad= True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()

  print(weights.grad)
  weights.grad.zero_()


tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
