In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30, 0.7, 1,0,0.5])

In [7]:
def mae(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt - yp)
    print("Total Error", y_true)
    mae = total_error / len(y_true)
    print("MAE: ", mae)
    return mae

In [8]:
mae(y_true, y_predicted)

Total Error [0.3 0.7 1.  0.  0.5]
MAE:  -0.1


-0.1

In [10]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [12]:
np.mean(y_predicted - y_true)

0.1

In [13]:
np.log([0.000])

C:\Users\Asad Computrs\AppData\Local\Temp\ipykernel_6372\1956594992.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0.000])


array([-inf])

In [14]:
eplison = 1e-15


In [18]:
y_predicted_new = [max(i, eplison) for i in y_predicted]

In [19]:
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [22]:
y_predicted_new = [min(i, 1-eplison) for i in y_predicted_new]

In [23]:
y_predicted_new

[0.999999999999999, 0.999999999999999, 0, 0, 0.999999999999999]

In [24]:
y_predicted_new = np.array(y_predicted_new)

In [26]:
np.log(y_predicted_new)

C:\Users\Asad Computrs\AppData\Local\Temp\ipykernel_6372\2469092518.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted_new)


array([-9.99200722e-16, -9.99200722e-16,            -inf,            -inf,
       -9.99200722e-16])

In [27]:
-np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*(np.log(1-y_predicted_new)))

C:\Users\Asad Computrs\AppData\Local\Temp\ipykernel_6372\3986142583.py:1: RuntimeWarning: divide by zero encountered in log
  -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*(np.log(1-y_predicted_new)))
C:\Users\Asad Computrs\AppData\Local\Temp\ipykernel_6372\3986142583.py:1: RuntimeWarning: invalid value encountered in multiply
  -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*(np.log(1-y_predicted_new)))


nan