In [1]:
print("Hello ")

Hello 


In [2]:
import torch

In [7]:
#x = torch.empty(3) // one day arry
x = torch.empty(2, 4)
print(x)
print(x.dtype)
print(x.size())

tensor([[-1.2388e+11,  4.5841e-41,  4.5129e-37,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])
torch.float32
torch.Size([2, 4])


In [9]:
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a)
print(b)
z = a+b
print(z)

tensor([[0.2283, 0.0811],
        [0.0999, 0.8943]])
tensor([[0.2466, 0.8859],
        [0.5218, 0.7617]])
tensor([[0.4749, 0.9671],
        [0.6218, 1.6560]])


In [10]:
s = torch.rand(5,2)
print(s)

tensor([[0.5945, 0.0913],
        [0.4812, 0.5395],
        [0.8599, 0.3109],
        [0.5227, 0.0936],
        [0.3447, 0.7347]])


In [12]:
#slicing technique
print(x[1, :])

tensor([0., 0., 0., 0.])


In [13]:
#Numpy to Torch tensor
import numpy as np

In [14]:
a = torch.ones(5)

In [15]:
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(type(b))

<class 'numpy.ndarray'>


In [17]:
#Torch tensor to numpy
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [18]:
b = torch.from_numpy(a)

In [19]:
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
