In [1]:
import torch
#import numpy as np

from quantum_circuit_simulator import quantum_circuit


'''
state_vector can 
(1) either be a vector of shape (dim,)
(2) either be a matrix of shape (dim, number of examples)

n is the number of qubits
dim = 2**n
'''

print()

## X, Y, Z gates

In [2]:
num_qubits = 1
dim = 2**num_qubits

state_vector = torch.arange(dim) + 1  # state_vector must be normalized
#state_vector = state_vector.reshape(-1,1)
qc = quantum_circuit(num_qubits = num_qubits, state_vector = state_vector)
print(qc.state_vector, '= initial state vector\n')

print(qc.n, '= n')
print(qc.dim, '= dim\n')
print(qc.I, '= I')
print(qc.x_matrix, '= X')
print(qc.y_matrix, '= Y')
print(qc.z_matrix, '= Z')

print(qc.h_matrix, '= H')

print(qc.proj_0, '= proj_0')
print(qc.proj_1, '= proj_1\n')


qc.x(0)
#qc.y(0)
#qc.z(2)

print(qc.state_vector, '= final state vector\n')



tensor([1.+0.j, 2.+0.j]) = initial state vector

1 = n
2 = dim

tensor([[1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j]]) = I
tensor([[0.+0.j, 1.+0.j],
        [1.+0.j, 0.+0.j]]) = X
tensor([[0.+0.j, -0.-1.j],
        [0.+1.j, 0.+0.j]]) = Y
tensor([[ 1.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j]]) = Z
tensor([[ 0.7071+0.j,  0.7071+0.j],
        [ 0.7071+0.j, -0.7071+0.j]]) = H
tensor([[1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]]) = proj_0
tensor([[0.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j]]) = proj_1

tensor([2.+0.j, 1.+0.j]) = final state vector



## H gate

In [3]:
num_qubits = 3
dim = 2**num_qubits

qc = quantum_circuit(num_qubits = num_qubits)
print(qc.state_vector, '= initial state vector\n')

qc.h(0)
qc.h(1)
print(qc.state_vector, '= final state vector\n')

tensor([[1.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j]]) = initial state vector

tensor([[0.5000+0.j],
        [0.0000+0.j],
        [0.5000+0.j],
        [0.0000+0.j],
        [0.5000+0.j],
        [0.0000+0.j],
        [0.5000+0.j],
        [0.0000+0.j]]) = final state vector



## Rx, Ry, Rz gates

In [4]:
num_qubits = 2
dim = 2**num_qubits


qc = quantum_circuit(num_qubits = num_qubits)
print(qc.state_vector, '= initial state vector\n')



ang_ = torch.rand(1, requires_grad=True)
ang=ang_[0]

print([torch.cos(ang/2), torch.sin(ang/2)], '\n')
print([torch.cos(ang), torch.sin(ang)], '\n')



#qc.Rx(0, ang)


qc.Ry(0, ang)

#qc.x(0)
#qc.Rz(0, ang)


print(qc.state_vector, '= final state vector\n')

tensor([[1.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j]]) = initial state vector

[tensor(0.9394, grad_fn=<CosBackward0>), tensor(0.3429, grad_fn=<SinBackward0>)] 

[tensor(0.7649, grad_fn=<CosBackward0>), tensor(0.6442, grad_fn=<SinBackward0>)] 

tensor([[0.9394+0.j],
        [0.0000+0.j],
        [0.3429+0.j],
        [0.0000+0.j]], grad_fn=<MmBackward0>) = final state vector



## general rotation R

In [5]:
num_qubits = 1
dim = 2**num_qubits


qc = quantum_circuit(num_qubits = num_qubits)
print(qc.state_vector, '= initial state vector\n')

ang_ = torch.rand(1, requires_grad=True)
ang=ang_[0]


print([torch.cos(ang/2), torch.sin(ang/2)], '\n')
print([torch.cos(ang), torch.sin(ang)], '\n')
zero = torch.tensor(0.0)


theta = zero #ang 
phi = zero #ang
lamda = ang #zero



qc.x(0)
qc.R(0, theta=theta, phi=phi, lamda=lamda)
print(qc.state_vector, '= final state vector\n')




tensor([[1.+0.j],
        [0.+0.j]]) = initial state vector

[tensor(0.9846, grad_fn=<CosBackward0>), tensor(0.1748, grad_fn=<SinBackward0>)] 

[tensor(0.9389, grad_fn=<CosBackward0>), tensor(0.3443, grad_fn=<SinBackward0>)] 

tensor([[0.0000+0.0000j],
        [0.9389+0.3443j]], grad_fn=<MmBackward0>) = final state vector



## CX, CZ gates

In [6]:
num_qubits = 3
dim = 2**num_qubits


state_vector = torch.arange(dim) + 1  # state_vector must be normalized
#state_vector = state_vector.reshape(-1,1)
qc = quantum_circuit(num_qubits = num_qubits, state_vector = state_vector)
print(qc.state_vector, '= initial state vector\n')

#qc.cx(control=0, target=1)
qc.cz(control=0, target=1)

print(qc.state_vector, '= final state vector\n')

tensor([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]) = initial state vector

tensor([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j, -7.+0.j, -8.+0.j]) = final state vector



In [7]:
num_qubits = 3
dim = 2**num_qubits

state_vector = torch.rand((dim, 2))  # state_vector must be normalized
qc = quantum_circuit(num_qubits = num_qubits, state_vector = state_vector)
print(qc.state_vector, '= initial state vectors\n')


#qc.cx(control=0, target=1)
qc.cz(control=0, target=1)

print(qc.state_vector, '= final state vector\n')

tensor([[0.3959+0.j, 0.0264+0.j],
        [0.7602+0.j, 0.7937+0.j],
        [0.6448+0.j, 0.6465+0.j],
        [0.3658+0.j, 0.4472+0.j],
        [0.9422+0.j, 0.6814+0.j],
        [0.5886+0.j, 0.2620+0.j],
        [0.3211+0.j, 0.7520+0.j],
        [0.6750+0.j, 0.4294+0.j]]) = initial state vectors

tensor([[ 0.3959+0.j,  0.0264+0.j],
        [ 0.7602+0.j,  0.7937+0.j],
        [ 0.6448+0.j,  0.6465+0.j],
        [ 0.3658+0.j,  0.4472+0.j],
        [ 0.9422+0.j,  0.6814+0.j],
        [ 0.5886+0.j,  0.2620+0.j],
        [-0.3211+0.j, -0.7520+0.j],
        [-0.6750+0.j, -0.4294+0.j]]) = final state vector



# cx_, cz_linear_layer

In [8]:
nn = 5

print(nn-2, nn-1)
for i in range(nn - 3, -1, -1):
    print(i, i+1)

3 4
2 3
1 2
0 1


In [9]:
num_qubits = 3
dim = 2**num_qubits

state_vector = torch.arange(dim) + 1  # state_vector must be normalized
#state_vector = state_vector.reshape(-1,1)
qc = quantum_circuit(num_qubits = num_qubits, state_vector = state_vector)
print(qc.state_vector, '= initial state vector\n')

''' 
cx_linear_layer applies cx(n-1,n) ... cx(2,3) cx(1,2) cx(0,1) |state_vector>

NOTE: First cx(0,1) will act on |state_vector>, then cx(1,2)
      And in the last cx(n-1,n) will act.
      order matter in case of cx
'''

qc.cx_linear_layer()

#qc.cz_linear_layer()
print(qc.state_vector, '= final state vector\n')

tensor([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]) = initial state vector

tensor([1.+0.j, 2.+0.j, 4.+0.j, 3.+0.j, 8.+0.j, 7.+0.j, 5.+0.j, 6.+0.j]) = final state vector



# Ry_layer

In [10]:
num_qubits = 2
dim = 2**num_qubits


qc = quantum_circuit(num_qubits = num_qubits)
print(qc.state_vector, '= initial state vector\n')



ang = torch.rand(num_qubits, dtype=torch.float, requires_grad=True)
print('ang =',ang)
ang = ang.to(torch.cfloat)   # = torch.complex(real=ang, imag=torch.zeros(num_qubits))
print('ang =',ang)



qc.Ry_layer(ang)

tensor([[1.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j]]) = initial state vector

ang = tensor([0.8070, 0.8190], requires_grad=True)
ang = tensor([0.8070+0.j, 0.8190+0.j], grad_fn=<ToCopyBackward0>)


tensor([[0.4724+0.j],
        [0.5053+0.j],
        [0.4932+0.j],
        [0.5275+0.j]], grad_fn=<MmBackward0>)